### ISSUE TITLE
How to create new product or update existing one?

### ISSUE THREAD

**Issue by Octales** [fabacus/node-magento2#1]
First of all, Thank you for making this great Magento rest module !

Can anyone please explain how to add data to a PUT method? For example if I want to edit or upload an image: this is what I have tried:
     
     var uploadPic= fs.createReadStream('Simple.png');
     mageClient.put('/V1/products/produs-1/media/1', {"file": uploadPic} )

Thanks !

**Comment by lilmuckers** [comment]
Hey! Sorry for the slow reply

That's exactly the right way to add data to the put method :).
But that's not the right way to submit data to the API - the format is off according to the Magento2 docs

First off you're using a read-stream handler - which you can't pass directly to the method, because it's not actually the contents of the file, just the pointer to the stream where the file contents will be coming from (I'm going to be adding helpers int he near future to handle this kinda stuff, but for now it doesn't exist).
Once you have the file contents, the contents need to be base64 encoded.

```javascript
//base64 encode file contents
var uploadPicB64 = fs.readFileSync('simple.png').toString('base64');

//create a new image
mageClient.post('/V1/products/produs-1/media', {
  "entry": {
    "label": "A Label",
    "disabled": false,
    "content": {
      "base64EncodedData": uploadPicB64,
      "name": "Image Name"
    }
  }
});
```

Updating an image would be much the same, except you'd need to pass the image id in the url on a put command.
